### ISSUE TITLE
GLPK    How to make GLPK_MI  stop  fastly

### ISSUE THREAD

**Issue by zhengdongxia** [newDemocracy-Foundation/selection-tool#6]
I can't understand this log, so I don't know how to get the optimal value quickly.This process is too slow！

Thanks for your reply

                              Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Apr 13 07:51:54 PM: Invoking solver GLPK_MI to obtain a solution.
      0: obj =   0.000000000e+00 inf =   7.325e+01 (51)
     15: obj =   0.000000000e+00 inf =   0.000e+00 (0)
*   482: obj =  -1.400000000e+01 inf =   6.800e-16 (0) 1
Long-step dual simplex will be used
+   482: mip =     not found yet >=              -inf        (1; 0)
+ 34283: >>>>>  -3.000000000e+00 >=  -1.200000000e+01 300.0% (333; 156)
+ 65044: mip =  -3.000000000e+00 >=  -1.100000000e+01 266.7% (853; 391)
+102959: mip =  -3.000000000e+00 >=  -1.100000000e+01 266.7% (1305; 713)
+141007: mip =  -3.000000000e+00 >=  -1.100000000e+01 266.7% (1743; 1028)
+176363: mip =  -3.000000000e+00 >=  -1.100000000e+01 266.7% (2084; 1428)
+211442: mip =  -3.000000000e+00 >=  -1.100000000e+01 266.7% (2425; 1785)
+247510: mip =  -3.000000000e+00 >=  -1.100000000e+01 266.7% (2789; 2166)
+283784: mip =  -3.000000000e+00 >=  -1.100000000e+01 266.7% (3166; 2476)
+318437: mip =  -3.000000000e+00 >=  -1.100000000e+01 266.7% (3501; 2802)
+353357: mip =  -3.000000000e+00 >=  -1.000000000e+01 233.3% (3748; 3122)
+389605: mip =  -3.000000000e+00 >=  -1.000000000e+01 233.3% (4203; 3568)
+425276: mip =  -3.000000000e+00 >=  -1.000000000e+01 233.3% (4610; 3984)
+461101: mip =  -3.000000000e+00 >=  -1.000000000e+01 233.3% (4995; 4408)
+495100: mip =  -3.000000000e+00 >=  -1.000000000e+01 233.3% (5402; 4878)
+530994: mip =  -3.000000000e+00 >=  -1.000000000e+01 233.3% (5761; 5303)
+565689: mip =  -3.000000000e+00 >=  -1.000000000e+01 233.3% (6167; 5689)
+598388: mip =  -3.000000000e+00 >=  -1.000000000e+01 233.3% (6530; 6119)
+632924: mip =  -3.000000000e+00 >=  -1.000000000e+01 233.3% (6863; 6501)

**Comment by luke-thorburn** [comment]
@zhengdongxia - Are you sure you have posted this issue in the right repository? The selection tool does not (currently) use the GLPK.

**Comment by luke-thorburn** [comment]
Closing this issue as it is not related to this repository.
